version: 2 
jobs: 
   build:    
    working_directory: ~/gdp-group-31-backend
    docker: 
    - image: circleci/openjdk:8-jdk-stretch 
    steps: 
      - checkout 
      - restore_cache:           
        key: gdp-group-31-backend-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline 
      - save_cache:
          paths:
            - ~/.m2
          key: gdp-group-31-backend-{{ checksum "pom.xml" }}
      - run: mvn package       
      - store_test_results: 
        path: target/surefire-reports
      - store_artifacts:
         path: target/Backend-1.0-SNAPSHOT.jar

